# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=123)),
                ('body', models.TextField()),
                ('event_date', models.CharField(blank=True, max_length=40)),
                ('start_time', models.TimeField(db_index=True, default='10:00')),
                ('end_time', models.TimeField(default='14:00')),
                ('event_type_id', models.IntegerField(blank=True, null=True)),
                ('event_standard', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
