# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(db_index=True, default='10:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
