# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160727_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type_id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'CLASS'), (6, 'EXAM'), (1, 'HOUSE'), (4, 'NATIONAL'), (5, 'RESTRICTED'), (3, 'SCHOOL')], default=3),
        ),
    ]
