# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160720_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
