# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 09:58
from __future__ import unicode_literals

import devices.models
from django.db import migrations, models
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', uuidfield.fields.UUIDField(db_index=True, max_length=32, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.IntegerField()),
                ('verification_code_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Verification Code Sent At')),
                ('verification_code_expires_at', models.DateTimeField(default=devices.models.expiry_time, verbose_name='Verification Code Expires At')),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
