# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=122)),
                ('options_type', models.CharField(choices=[('1', 'single'), ('2', 'multiple')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiredAt', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=155)),
                ('poll_type', models.CharField(choices=[('1', 'school'), ('2', 'standard')], max_length=1)),
                ('option_id', models.CharField(blank=True, max_length=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_poll_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_poll_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
