# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='options_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'MULTIPLE'), (1, 'SINGLE')], default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='poll',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'CLASS'), (1, 'SCHOOL')], default=1),
        ),
    ]
