# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=122)),
                ('options_type', models.CharField(choices=[('1', 'single'), ('2', 'multiple')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
