# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homework', models.TextField()),
                ('subjectID', models.CharField(blank=True, max_length=12)),
                ('standardId', models.CharField(blank=True, max_length=12)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('teacherId', models.CharField(blank=True, max_length=12)),
                ('lastdate', models.DateField(blank=True)),
            ],
        ),
    ]
