# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Subject'),
        ),
    ]
