# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 07:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=233)),
                ('body', models.TextField()),
                ('category_id', models.CharField(blank=True, max_length=122)),
                ('against_id', models.CharField(blank=True, max_length=122)),
                ('anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[(0, 'open'), (1, 'closed'), (2, 'reopen')], max_length=12)),
                ('closedDate', models.DateTimeField()),
                ('assignedTo', models.CharField(blank=True, max_length=122)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_complaint_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_complaint_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('complaint_id', models.CharField(blank=True, max_length=1)),
                ('employee_id', models.CharField(blank=True, max_length=1)),
                ('parent_id', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
