# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20160727_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Assigned'), (2, 'Closed'), (1, 'Open'), (4, 'Reopen')], default=1),
        ),
    ]
