# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20160727_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintcomment',
            name='complaint_id',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='closedDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
