# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20160801_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='closedDate',
            field=models.DateField(blank=True),
        ),
    ]
