# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20160729_0749'),
        ('complaints', '0005_auto_20160801_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComplaint',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=233)),
                ('body', models.TextField()),
                ('against_id', models.CharField(blank=True, max_length=122)),
                ('anonymous', models.BooleanField(default=True)),
                ('closedDate', models.DateField(blank=True)),
                ('assignedTo', models.CharField(blank=True, max_length=122)),
                ('status', models.PositiveSmallIntegerField(choices=[(3, 'Assigned'), (2, 'Closed'), (1, 'Open'), (4, 'Reopen')], default=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.Category')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical complaint',
            },
        ),
        migrations.CreateModel(
            name='HistoricalComplaintComment',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('comment', models.TextField()),
                ('employee_id', models.CharField(blank=True, max_length=1)),
                ('parent_id', models.CharField(blank=True, max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical complaint comment',
            },
        ),
    ]
